"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://splatoonwiki.org/wiki/Main_Page
  name = splatoonwiki

Please do not commit this to the Git repository!
"""
from abc import ABC

from pywikibot import family


class Family(family.Family, ABC):  # noqa: D101

    name = 'splatoonwiki'
    langs = {
        'en': 'splatoonwiki.org',
        'es': 'es.splatoonwiki.org',
        'fr': 'fr.splatoonwiki.org',
    }

    def scriptpath(self, code):
        return '/w'

    def protocol(self, code):
        return 'https'
