TOPICS = (
    "acting experiences",
    "addition",
    "what are you afraid of",
    "after Alterna",
    "composition of air",
    "answer to universe, life, and everything",
    "anyone you look up to",
    "a time you remember fondly",
    "apple types",
    "interesting areas around you",
    "arms",
    "around the world",
    "art",
    "what makes autumn/fall great?",
"Atari 2600 games",
"anger management solutions",
"ancient history",
"animals",
"alpine skiing",
"a trophy you've won",
"a way out of this tricky situation",
"Al Yankovic",
"arches",
"arctic or antarctic?",
"antonyms",
"an actor/actress you admire",
"ASMR",
"Albuquerque",
    "bags",
    "bears",
    "what do you find beautiful?",
    "going to bed",
    "what makes your bedroom unique?",
    "what you did earlier today",
    "beginning of time",
    "bells",
    "big brain time",
    "birds",
    "birthdays",
    "minecraft blocks",
    "boardgames",
    "boats",
    "broken bones (no blood)",
    "what borders your country?",
    "you have an empty bottle. What do you fill it with?",
    "what is your favourite bowl material?",
    "cats in boxes",
    "what makes you brave?",
    "bread",
    "what do you do on your break-time?",
    "breakfast",
    "remember that you're breathing",
    "bridges",
    "brightness",
    "brothers",
    "brushes",
    "buildings and architecture",
    "buses",
    "what keeps you busy?",
    "what do you like to buy?",
"blobs",
"belt buckles",
"brooms",
"booze",
"your boss",
"where the hell is the boss",
"beets",
"battlestar galactica",
"burgeoning spiderworts",
"bop-it",
"blue things",
"something with blueberries",
"baskets",
"things that make a 'boing' sound",
"you're writing a book…what's the subject?",
"old billy bob down by the creek",
"something that gets boiled",
"bogos binted",
"do you, or do you not, feel bonita?",
    "cake",
    "calling people",
    "can can 💃",
    "candles",
    "hats, caps, and no cap",
    "cars",
    "cards",
    "that time you carried",
    "cats",
    "what interesting things are there in your city center?",
    "what are you certain of?",
    "define a chair",
    "luck & chance",
    "how do you manage change",
    "cheese",
    "chickens",
    "chocolate",
    "choice",
    "circles & shapes",
    "your favourite cities",
    "cleaning your room",
    "climbing",
    "clocks & time",
    "clothes",
    "clouds",
    "closing the goddamn door",
    "coats",
    "coins",
    "cold",
    "collections",
    "colours",
    "something that's comfy",
    "what have you recently completed?",
    "computers",
    "cooking",
    "something that is cool",
    "counting",
    "race courses",
    "you have a crash mat... what do you use it for?",
    "cross-stitching",
    "cups",
"C side fish",
"Cinco de Mayo",
"chivalry",
"Coke or Pepsi?",
"covers",
"corrosion",
"your favorite way to prepare carrots",
"cassette tapes",
"CDs",
    "dancing",
    "what did you do that was dangerous?",
    "darkness",
    "day time",
    "deep sea",
    "deer & does",
    "desks",
    "isn't it great to be different?",
    "what did you overcome that was difficult?",
    "I wonder what's for dinner?",
    "direction",
    "new discoveries",
    "dogs",
    "dreams",
    "what's your go-to dress style?",
    "favourite drinks",
    "driving",
    "ducks",
"Discord",
"diet soda or regular?",
"do it",
"dunking",
"doughnuts",
"donuts",
"delicious things",
"disgusting things",
"dollies and action figures",
"dressing up",
"destiny",
"Prelude in D minor, BWV 926",
"duties you've been neglecting",
"dumb luck",
"dreams related to BBQ",
"dark chocolate or milk chocolate?",
"dungeons",
"digital or analog?",
    "Earth",
    "what do you find easy?",
    "education",
    "eggs",
    "Eight",
    "electric things & electricity",
    "elephants",
    "is the glass empty?",
    "what do you enjoy?",
    "escape ropes",
    "evenings & sunset",
    "how are the exams going?",
    "what are you excited for?",
    "exercise, routines & training",
    "what are you expecting?",
    "what's expensive to you?",
    "eyes",
"events",
"everlasting love",
"eavesdropping",
"e eats everything",
"estrogen",
"extensions",
"Elmo",
"evens or odds",
"even flows",
"odd flows",
"electric guitar or acoustic guitar?",
"evil",
"elbows",
"elliptical objects",
"elongating",
"everything in its right place",
    "give us a fact",
    "this statement is false",
    "someone famous & celebrities",
    "farms",
    "what's fast?",
    "what do you fear?",
    "how are you feeling?",
    "films & directors",
    "fish & crustaceans",
    "flags & patterns",
    "name something that floats",
    "make something out of flour",
    "flowers",
    "flying",
    "food",
    "forces & physics",
    "forests",
    "chopsticks, knives, forks, or spoons?",
    "foxes",
    "friendship",
    "fruit",
    "what do you find fun?",
    "something funny",
    "furniture",
    "future",
"*fart_sound_fx.mp3*",
"faries",
"filling up",
"floating things",
"something final",
"fitness",
"feeling gravity's pull",
"Fortnite",
    "games",
    "gardens",
    "gifts",
    "giving",
    "what are you glad about?",
    "glasses",
    "goats",
    "what does it mean to be good?",
    "touching grass",
    "ground & biomes",
"gray",
"grey",
"gallons",
"gases",
"goggles",
"gumbo",
"gullies and gulches",
"seagulls",
"glowing",
"growing up",
"the mysterious goo behind the fridge",
"garfield",
"gemstones",
"going places",
"ghosts, spectres, or spirits",
"a masterful gambit",
"galloping",
"gophers",
"chewing gum",
"Gru",
"Geese. Yes or no?",
    "hair types and colours",
    "hammer time",
    "what sounds can you hear?",
    "hearts",
    "hello & world greetings",
    "hide and (go) seek",
    "something high up",
    "hills",
    "holidays and vacationing",
    "your hopes",
    "horses",
    "what's hot right now?",
"hotel california",
"what does home mean to you?",
"how",
"heads",
"hyenas",
"something hefty",
    "ouch, Charlie (memes)",
    "slipping on the ice & skating",
    "what's important to you",
    "introduce yourself",
    "inventions",
    "islands",
"inversions",
"something interesting",
"innie or outie?",
"iPhone or Android?",
"I can't remember. Can you remind me?",
"Ichabod Crane",
"something iconic",
"something ironic",
"something impressive",
"imps",
"igneous rocks",
"something you're iffy about",
"ice cream",
"ivy",
"if you could imbue your soul into an object, what would you pick?",
    "jelly",
    "juice",
"Jamiroquai",
"jungles",
"a time you were jealous",
"junk",
"Jimmy Neutron",
"jaws, teeth, or dental procedures",
"jacks",
"jigs",
"jigsaw puzzles",
    "kings & history",
"kettles",
"a random act of kindness",
"kilts and skirts",
"ketchup",
"what's in your kitchen?",
"something kissable",
"all the king's horses and all the king's men",
"your favorite Korean food",
"chicken, Kentucky Fried or otherwise",
"something kafkaesque",
"kittens",
"something to keep",
"karats, gold, and diamonds",
    "knowledge, books, and power",
    "candles, lamps, or bulbs?",
    "when were you last late?",
    "what makes you laugh?",
    "learnding (Simpsons)",
    "letters and calligraphy",
    "libraries",
    "should you always tell the truth?",
    "lions & pride",
    "something little",
    "locks & picking",
    "what took you a long time?",
"loops",
"something (or someone!) you love",
"something large",
"do you like learning/school?",
"left",
"if you won the lottery, what would you spend the money on?",
"the last something",
"lasers",
"lava",
"the last time you did the laundry",
"a time you lost",
"loud things",
    "machines",
    "maps & cartography",
    "stands, markets, and malls",
    "matter & antimatter",
    "mindfulness, meditation, and thinking",
    "models",
    "monkeys",
    "the moon & astrology",
    "mornings & sunrise",
    "mountains",
    "movement, swimming, dancing",
    "music, noise, and sound",
"memories",
"mastery of a subject",
"mayonnaise",
"mixing",
"hey those floors needed mopped, can you get that",
"mice, rats, and other rodents",
"Marvel",
"a time you were mad",
"what's your dream location to be married?",
    "names",
    "nature",
    "nets",
    "what's new with you?",
    "nighttime & darkness",
    "nobles & historical figures",
    "numbers & math(s)",
"noise",
"neon signs",
"what never to do",
"nighttime showers or morning showers?",
    "the ocean",
    "the office",
    "oil & fossils",
    "something older than you",
    "opposite day",
    "can I take your order?",
    "other worlds & space",
    "the outside",
"what if i could offer you something that could change your life forever?",
"optics",
"optical illusions",
"the oiliest, greasiet food you can think of",
"a bad omen",
"a good omen",
"orange",
"something organic",
"church organs",
"Ontario",
"Ohio",
"owls",
    "paint & art",
    "pans",
    "the park",
    "parties",
    "how do we achieve peace?",
    "pens, pencils, crayons & stationery",
    "salt n pepper",
    "what's perfect?",
    "photographs",
    "pianos & keyboards",
    "pictures",
    "pigs",
    "check the pins!",
    "what's your favourite place?",
    "plants & trees",
    "plays, performances & theatre",
    "pockets (or lack of!)",
    "politeness",
    "popularity",
    "the art of the possible",
    "potatoes, chips, & everything you can make with them",
    "the press & media",
    "something pretty",
    "the price is right",
    "prizes",
    "how would you define a problem? How would you solve it?",
    "what have you promised?",
    "what will you protect?",
"pillows",
"something with a lot of pieces",
"something (or someone!) precious to you",
"pine trees",
"pewter",
"peetah. the horse is here.",
"paws",
"puzzles",
"popcorn",
"pilk",
"plowing the fields on a dark summer night during the harvest moon in complete silence and isolation, finding inner peace despite the turmoil posed by the farm being less bountiful this year and the markets being less forgiving"
"pumpkin or pumpkin spice foods and drinks",
"pie",
"perchance",
    "queens & history",
    "question time! Your next message must be a question.",
"quills",
"something quintessential",
    "something quick",
    "something quiet",
"quinacridone",
    "radios & transmission",
    "rain & weather",
    "what do you do on a rainy day?",
    "reading & books",
    "what do you need to get ready?",
    "reality, VR, and The Matrix",
    "world records",
    "remind me of a thing that happened?",
    "what can you repair?",
    "restaurants & places to eat",
    "rice & everything you can make with rice",
    "rides & roller-coasters",
    "rocks, stones, and geodes",
    "running & racing",
    "rush B! (memes or CS)",
"Rush E! (meme music)",
"records of the vinyl kind",
"real estate",
"roots",
"what roils your mood?",
"something raw",
"repossession",
"a sentence not containing the glyph 'R'",
"rims or borders",
    "safety",
    "sails & sailing",
    "sand & sea",
    "saving & loading",
    "science & technology",
    "searching & search engines",
    "sentences, words, language, and grammar",
    "lambs & sheep",
    "ships",
    "shoes & footwear",
    "shows & programmes",
    "last time you got sick",
    "if a tree falls and no one is around to hear it, is this cliche?",
    "singing",
    "sisters",
    "the sky",
    "sleep & dreaming",
    "something slow",
    "smoking & vaping",
    "snow & snowball fights",
    "something soft",
    "soup",
    "something special",
    "what is speed?",
    "spells & magic",
    "what makes spring great?",
    "stamps & collecting",
    "stars & constellations",
    "steam",
    "storms",
    "stories",
    "something strong",
    "studying",
    "what is success?",
    "sugar",
    "what makes summer great?",
    "sun & sunshine",
    "surprises",
    "something sweet",
    "swimming",
    "swords",
"something yucky",
"stitching",
"supercalifragilisticexpialidocious",
"something structurally sound",
    "something tasty",
    "taxis",
    "teaching",
    "telephones & mobiles",
    "television",
    "tennis & badminton",
    "titles",
    "what's happening tomorrow?",
    "what's happening tonight?",
    "touching & sensing",
    "trains & trams",
    "travel & vacation",
    "trust",
    "typing on PC vs mobile",
"when is ten of something better than twenty",
"typefaces and fonts",
"towns",
"turnips and other earthen vegetables",
"tiramisu",
"tea",
"omigawd what's the tea, sis",
"trig jegman was here",
"tungsten is pretty heavy. how much can you lift, bro?",
"what's a monthly target for your aspirations?",
"THICK JERKY",
"what's your favorite magic trick?",
    "fruit & vegetables",
    "voices & how they vary",
"variations",
"versions",
"do you have vertigo?",
"vultures",
"voltron",
"villains and henchment",
"vanilla-flavored things",
"something that vexes you",
    "waking up routine",
    "what do you want & wish for?",
    "warmth & fuzzies",
    "watches",
    "weddings",
    "what can I say except... you're welcome?",
    "something wild",
    "windows",
    "what makes winter great?",
    "make a wish!",
"wonder",
"the big willow tree out down by the lake where we used to run and play",
"witchcraft and sorcery",
"the coolest woman",
"wyoming",
"waste",
"who do you want to be today?"
    "what happened yesterday?",
"yearning",
"where do you see yourself in a year?",
"yule",
"yellow objects",
"yawning….made you do it!",
"yowch! a time you were hurt",
"advice you'd give to younger you",
    "zoos",
"something zesty",
"zamboni",
    "what is your favourite thing that's blue?",
    "what's your favourite thing that's gold?",
    "what's your favourite thing that's grey?",
    "what's your favourite thing that's orange?",
    "what's your favourite thing that's red?",
    "what's your favourite thing that's silver?",
    "the creatures are coming, and you cannot outrun them. What will you do?",
    "what's the best vacation you've ever had?",
    "do you have any pets?",
    "what are your hobbies?",
    "what's your favourite book?",
    "what's the most interesting place you've ever visited?",
    "if you could have dinner with any historical figure, who would it be?",
    "what's your favourite movie?",
    "do you prefer coffee or tea?",
    "what's your favourite season and why?",
    "do you enjoy cooking? What's your signature dish?",
    "what's the most memorable concert you've been to?",
    "do you play any musical instruments?",
    "what's your dream job?",
    "what's the best advice you've ever received?",
    "what's your favourite way to spend a weekend?",
    "do you have any siblings?",
    "what's your favourite type of music?",
    "what's the best gift you've ever received?",
    "if you could live anywhere in the world, where would it be?",
    "what's your favourite type of cuisine?",
    "what's your favourite holiday and why?",
    "do you have any phobias?",
    "what's your favourite childhood memory?",
    "what's the last book you read?",
    "what's your favourite outdoor activity?",
    "if you could meet any celebrity, who would it be?",
    "do you enjoy travel? What's your favourite destination?",
    "what's your favourite TV show?",
    "what's the most unusual thing you've ever eaten?",
    "do you have a favourite quote or saying?",
    "what's the best prank you've ever pulled?",
    "what's your favourite animal?",
    "what's your favourite board game?",
    "do you have any hidden talents?",
    "what's your favourite flower?",
    "if you could time travel, would you go to the past or the future?",
    "what's your favourite sports team?",
    "what's your favourite dessert?",
    "what's your favourite way to relax?",
    "what's your favourite app on your phone?",
    "what's your favourite type of art?",
    "do you have a favourite podcast?",
    "what's your favourite thing to do on a rainy day?",
    "do you collect anything?",
    "what's your favourite form of exercise?",
    "what's your favourite type of weather?",
    "do you believe in ghosts or the supernatural?",
    "what's your favourite color?",
    "what's your favourite snack?",
    "do you have a favourite charity or cause you support?",
    "what's your favourite way to spend a day off?",
    "what's the best compliment you've ever received?",
    "what's your favourite way to stay organized?",
    "what's your favourite kind of sandwich?",
    "what's your favourite movie genre?",
    "do you prefer the beach or the mountains?",
    "what's your favourite type of tree?",
    "what's your favourite game to play on your phone?",
    "what's your favourite mode of transportation?",
    "what's your favourite fruit?",
    "do you have a favourite superhero?",
    "what's your favourite type of pie?",
    "what's your favourite way to celebrate your birthday?",
    "what's your favourite breakfast food?",
    "what's the best job you've ever had?",
    "what's your favourite insect?",
    "what's your favourite type of cheese?",
    "what's your favourite clothing brand?",
    "what's your favourite subject in school?",
    "what's your favourite fast food restaurant?",
    "what's your favourite ice cream?",
    "do you prefer sunrises or sunsets?",
    "what's your favourite song?",
    "what's your favourite kind of soup?",
    "what's your favourite family tradition?",
    "what's your favourite type of footwear?",
    "what's your favourite social media platform?",
    "what's your favourite thing about your home or town?",
    "what's your favourite guilty pleasure?",
    "what's your favourite thing to do in the snow?",
    "what's your favourite kind of flower?",
    "what's your favourite childhood toy?",
    "what's your favourite way to unwind after a long day?",
    "what's your favourite holiday tradition?",
    "what's your favourite thing to cook?",
    "what's your favourite comfort food?",
    "what's your favourite workout?",
    "what's your favourite type of fish?",
    "what's your favourite thing about your job?",
    "what's your favourite thing to do on a road trip?",
    "what's your favourite guilty pleasure TV show?",
    "what's your favourite way to keep in touch with friends?",
    "what's your favourite way to spend a lazy day?",
    "what's your favourite amusement park ride?",
    "what's your favourite kind of cake?",
    "what's your favourite movie soundtrack?",
    "what's your favourite thing to do in your free time?",
    "what's your favourite city?",
    "what's your favourite type of seafood?",
    "what's your favourite type of bread?",
    "what's your favourite thing to do on a Saturday night?",
    "what's your favourite app?",
    "what's your favourite way to enjoy nature?",
    "what's your favourite thing to do at the beach?",
    "what's your favourite salad dressing?",
    "what's your favourite type of sandwich?",
    "what's your favourite part of your daily routine?",
    "what's your favourite kind of juice?",
    "what's your favourite thing about the weekend?",
    "what's your favourite vegetable?",
    "what's your favourite childhood game?",
    "what's your favourite ice cream topping?",
    "what's your favourite way to spend time with family?",
    "what's your favourite candy?",
    "what's your favourite way to stay cool in the summer?",
    "what's your favourite way to warm up in the winter?",
    "what's your favourite kind of soda?",
    "what's your favourite way to spend a holiday?",
    "what's your favourite way to celebrate special occasions?",
    "what's your favourite family recipe?",
    "what's your favourite way to stay hydrated?",
    "what's your favourite type of pizza?",
    "what's your favourite way to show someone you care?",
    "what's your favourite way to spend a quiet evening?",
    "what's your favourite way to explore a new place?",
    "what's your favourite thing to do on a long flight?",
    "what's your favourite way to make someone smile?",
    "what's your favourite way to end a long day?",
    "what's your favourite way to enjoy a sunny day?",
    "what's your favourite way to stay motivated?",
    "what's your favourite way to stay active?",
    "what's your favourite way to enjoy the outdoors?",
    "what's your favourite way to start the day?",
    "what's your favourite way to celebrate your birthday?",
    "what's your favourite way to treat yourself?",
    "what's your favourite thing about your favourite sport?",
    "what's your favourite way to make new friends?",
    "what's your favourite thing about your favourite season?",
    "what's your favourite way to show gratitude?",
    "what's your favourite way to celebrate milestones?",
    "what's your favourite way to enjoy a good book?",
    "what's your favourite way to explore nature?",
    "what's your favourite way to stay positive?",
    "what's your favourite way to enjoy music?",
    "what's your favourite way to stay healthy?",
    "what's your favourite way to bond with family?",
    "what's your favourite way to spend a cozy evening?",
    "what's your favourite way to stay organized?",
    "what's your favourite way to learn something new?",
    "what's your favourite way to enjoy the little things in life?",
    "what's your favourite way to spend a long weekend?",
    "what's your favourite way to unwind after work?",
    "what's your favourite way to stay entertained?",
    "what's your favourite way to enjoy quiet time?",
    "what's your favourite way to stay focused?",
    "what's your favourite way to spend a summer day?",
    "what's your favourite way to enjoy a winter day?",
    "what's your favourite way to celebrate success?",
    "what's your favourite way to support your community?",
    "what's your favourite way to enjoy a meal?",
    "what's your favourite way to make a difference?",
    "what's your favourite way to enjoy a hobby?",
    "what's your favourite way to spend a special occasion?",
    "what's your favourite type of tree?",
    "if you could live in any era, which one would it be?",
    "what's your favourite thing to do on a Sunday?",
    "what's your favourite kind of fruit juice?",
    "what's your favourite thing about the city you live in?",
    "what's your favourite kind of tea?",
    "what's your favourite book genre?",
    "what's your favourite comfort movie?",
    "what's your favourite thing to do in the fall?",
    "what's your favourite car brand?",
    "what's your favourite historical event?",
    "what's your favourite subject to learn about?",
    "what's your favourite place to go for a walk?",
    "what's your favourite type of flower arrangement?",
    "what's your favourite thing to do on a sunny day?",
    "what's your favourite way to relax at the end of the day?",
    "what's your favourite thing to do when you're bored?",
    "what's your favourite type of exercise?",
    "what's your favourite type of houseplant?",
    "what's your favourite way to enjoy a movie night?",
    "what's your favourite way to support local businesses?",
    "what's your favourite thing to do in the spring?",
    "what's your favourite memory from high school?",
    "what's your favourite way to spend a holiday weekend?",
    "what's your favourite type of chocolate?",
    "what's your favourite type of festival?",
    "what's your favourite classic movie?",
    "what's your favourite room in your house?",
    "what's your favourite type of puzzle?",
    "what's your favourite childhood TV show?",
    "what's your favourite type of bread to bake?",
    "what's your favourite way to decorate for the holidays?",
    "what's your favourite type of flower to grow?",
    "what's your favourite way to get around town?",
    "what's your favourite type of photography?",
    "what's your favourite way to celebrate New Year's?",
    "what's your favourite thing about summer?",
"why not?",
"would you switch which hand is your dominant one?",
"would you rather never have to pay for transportation (gas, public transit, ride share) or for housing (rent, mortgage)?",
"Why do they call it oven when you of in the cold food of out hot eat the food?",
"How much could a woodchuck chuck if a woodchuck could chuck wood?",
"What's in your wallet?",
"Can you burn a Luigi board?",
"What's it all about?",
"Are people even still reading these?",
"You know who ELSE wants a topic?",
"What is cooler than being cool?",
"Do you tend to look to the future or the past?",
"Light mode or dark mode?",
"Times New Roman or Arial?",
"Is there anything better than a cold hotel room?",
"What's your favorite conspiracy theory?",
"Werewolves or vampires?",
)


TOPICS_FR = (
    "si vous êtes un bon acteur",
    "d'additions et soustractions",
    "de ce dont vous avez peur",
    "d'au-delà d'Alterna",
    "de l'air",
    "de la réponse à l'univers, la vie et tout le reste",
    "de n'importe quoi sauf ce dont vous parlez maintenant",
    "de quelqu'un que vous admirez",
    "d'un moment dont vous gardez un bon souvenir",
    "depommes",
    "de lieux intéréssants autour de vous",
    "de bras",
    "de choses autour du monde",
    "de l'art",
    "de votre tante",
    "de ce qui rend l'automne génial ?",
    "de sacs",
    "de tennis",
    "d'haricots",
    "d'ours",
    "de ce que vous trouvez beau ?",
    "d'aller au lit",
    "de ce qui rend votre chambre unique ?",
    "d'avant votre arrivée sur Inkipédia",
    "du début du temps",
    "de ce qu'il y a derrière le masque",
    "de cloches",
    "du meilleur ... ???",
    "d'un big brain time",
    "d'oiseaux",
    "d'anniversaires",
    "de blocs de Minecraft",
    "de votre chose préférée qui est bleue ?",
    "de jeux de société",
    "de bateaux",
    "d'os brisés (sans sang)",
    "de livres",
    "de ce qui borde la frontière de votre pays ?",
    "d'où vous êtes né ?",
    "vous avez une bouteille vide. Avec quoi la remplissez-vous ?",
    "de votre matériau préféré pour un bol  ?",
    "de boîtes",
    "de ce qui vous rend courageux ?",
    "de pain",
    "de ce que vous faites pendant votre pause ?",
    "du petit-déjeuner",
    "de la respiration",
    "de ponts",
    "de la lumière",
    "de frères",
    "de votre chose préférée qui est marron ?",
    "de brosses",
    "de bâtiments",
    "du bus",
    "de ce qui vous garde occupé ?",
    "de ce que vous aimez acheter ?",
    "de gâteau",
    "d'appeler des gens",
    "du cancan",
    "de bougies",
    "de casquettes",
    "de voitures",
    "de cartes",
    "de ce moment où vous avez carry",
    "de chats",
    "de ce qu'il y a dans votre centre-ville ?",
    "du coup de génie du siècle",
    "de ce dont vous êtes certain ?",
    "de chaises",
    "de chance",
    "de changement",
    "de fromage",
    "de poules",
    "de chocolat",
    "de choix",
    "de cercles",
    "de villes",
    "des cours",
    "de nettoyage",
    "d'escalade",
    "d'horloges",
    "de vêtements",
    "de nuages",
    "de fermer la porte, bon sang",
    "de café",
    "de manteaux",
    "de pièces de monnaie",
    "du froid",
    "de collections",
    "de couleurs",
    "de quelque chose de confortable",
    "de ce que vous avez récemment terminé ?",
    "d'ordinateurs",
    "de cuisine",
    "de quelque chose de cool",
    "de compter",
    "de circuits de course",
    "de on vous donne un Crash Mat... vous l'utilisez pour faire quoi ?",
    "de faire de la broderie",
    "de tasses",
    "de danser",
    "de ce que vous avez fait de dangereux dans votre vie ?",
    "de l'obscurité",
    "de quand il fait jour",
    "des abysses",
    "de cerfs",
    "des bureaux",
    "de ce que vous voulez détruire ?",
    "de si ce n'est pas génial d'être différent ?",
    "de ce que vous avez surmonté qui était difficile ?",
    "de je me demande ce qu'il y a pour le dîner ?",
    "de directions",
    "de nouvelles découvertes",
    "de chiens",
    "de rêves",
    "de votre style vestimentaire préféré ?",
    "de boissons préférées",
    "de conduire",
    "de canards",
    "de la Terre",
    "de ce que vous trouvez facile ?",
    "d'éducation",
    "d'œufs",
    "du chiffre huit",
    "d'objets électriques",
    "d'éléphants",
    "si le verre est vide ?",
    "de ce que vous appréciez ?",
    "de cordes pour s'enfuir",
    "de soirées",
    "de comment se passent les examens ?",
    "de ce qui vous rend enthousiaste en ce moment ?",
    "d'entraînement",
    "de ce que vous attendez ?",
    "de ce qui est cher pour toi ?",
    "d'œil",
    "de visages",
    "nous donner un fait",
    "de cette déclaration est fausse",
    "de quelqu'un de célèbre",
    "de fermes",
    "de ce qui est rapide ?",
    "de ce que vous craignez ?",
    "de comment vous vous sentez ?",
    "de quand vous avez eu de la fièvre pour la dernière fois ?",
    "de si vous avez déjà faparticipé à un combat ?",
    "de films",
    "de ce qui est considéré comme des doigts ?",
    "ce que sont les doigts ?",
    "de poissons",
    "de drapeaux",
    "afin de nommer quelque chose qui flotte",
    "de faire quelque chose avec de la farine",
    "de fleurs",
    "de pouvoir voler dans les airs",
    "de nourriture",
    "de football",
    "de force",
    "de forêts",
    "de fourchettes",
    "de renards",
    "de la liberté",
    "d'amitié",
    "de fruits",
    "de ce que vous trouvez amusant ?",
    "de quelque chose de drôle",
    "de meubles",
    "de l'avenir",
    "de jeux",
    "de jardins",
    "de cadeaux",
    "d'offrir",
    "de ce dont vous êtes contents",
    "de lunettes",
    "de chèvres",
    "de votre objet doré préféré",
    "de ce que la bonté ?",
    "de grands-parents",
    "d'herbe",
    "de votre objet vert préféré ?",
    "de votre objet gris préféré ?",
    "du sol",
    "de votre groupe préféré ?",
    "de cheveux",
    "de hammer time",
    "de mains",
    "de chapeaux",
    "de ce qui est bon pour la santé",
    "d'ouïe",
    "de ce qui est lourd ?",
    "de cœurs",
    "d'hauteur",
    "et vous dire bonjour",
    "de poules",
    "de cacher quelque chose puis d'essayer de le trouver",
    "de quelque chose de haut",
    "de collines",
    "de loisirs",
    "de vacances et voyages",
    "de votre maison",
    "de vos espoirs",
    "de chevaux",
    "de ce qui est à la mode en ce moment ?",
    "de maisons",
    "d'où est Charlie",
    "de glace",
    "de vos bonnes idées",
    "de ce qui est important pour vous",
    "de vous présenter",
    "d'inventions",
    "de quelque chose en fer",
    "d'îles",
    "de gelée (comestible)",
    "de jus",
    "de clés",
    "de rois",
    "de genoux",
    "du savoir",
    "d'échelles",
    "de lampes",
    "de quand vous avez été en retard pour la dernière fois",
    "de ce qui vous fait rire ?",
    "d'une feuille",
    "d'apprentissage",
    "de lettres et calligraphie",
    "de bibliothèques",
    "de quand vous avez menti pour la dernière fois",
    "de lions",
    "de quelque chose de petit",
    "de verrous",
    "de ce qui vous a pris du temps",
    "de chance",
    "de machines",
    "de cartes",
    "de marchés",
    "de matière",
    "de repas",
    "de mesurer des choses",
    "de votre conscience",
    "de minutes",
    "de modèles",
    "de la modernité",
    "de singes",
    "de mois",
    "de lunes",
    "du matin",
    "de montagnes",
    "de mouvement",
    "de musique",
    "de noms",
    "de la nature",
    "de voisins",
    "de filets",
    "de quoi de neuf",
    "de nouvelles",
    "de ce qui est agréable",
    "de la nuit",
    "de nobles",
    "du bruit",
    "de nombres",
    "de l'océan",
    "du bureau",
    "d'huile",
    "de quelque chose de vieux",
    "du jour de l'opposé",
    "de votre objet orange préféré ?",
    "de si je peux prendre votre commande ?",
    "d'autres mondes",
    "de l'extérieur",
    "de peinture",
    "de poêles",
    "de parents",
    "du parc",
    "de la fête",
    "de comment atteindre la paix ?",
    "de stylos",
    "de crayons",
    "du poivre",
    "de ce qui est parfait ?",
    "de photographies",
    "de pianos",
    "d'images",
    "de cochons",
    "d'épingles",
    "de votre objet rose préféré ?",
    "de votre endroit préféré ?",
    "de plantes",
    "de jouer",
    "de poches",
    "de poison",
    "de la politesse",
    "de popularité",
    "de l'art du possible",
    "de pommes de terre",
    "de pouvoir",
    "de presse",
    "de quelque chose de joli",
    "du juste prix",
    "de prix",
    "de votre problème ?",
    "des promesse que vous avez faites ?",
    "de ce que vous voudriez protéger ?",
    "du public",
    "de reines",
    "temps de question ! Votre prochain message doit être une question.",
    "de quelque chose de rapide",
    "de quelque chose de silencieux",
    "de radios",
    "de la pluie",
    "de jours de pluie",
    "de lecture",
    "de ce dont vous avez besoin pour vous préparer ?",
    "de la réalité",
    "de records du monde",
    "de votre objet rouge préféré ?",
    "de vous rappeller un de vos souvenirs",
    "de vous rappeller quelque chose",
    "de ce dont vous pouvez réparer ?",
    "de mentions de réponse",
    "de restaurants",
    "du riz",
    "d'attractions et montagnes russes",
    "du lever du soleil",
    "de routes",
    "de rochers",
    "de votre objet en caoutchouc préféré ?",
    "de course à pied",
    "de rush B",
    "de sécurité",
    "de voiles de bateaux",
    "du sel",
    "du sable",
    "de sauvegardes",
    "de l'école",
    "de la science",
    "de ciseaux",
    "de recherche",
    "de sièges",
    "de choses à vendre",
    "d ephrases",
    "d'ombres",
    "de formes",
    "de feutres",
    "de moutons",
    "d'étagères",
    "de bateaux",
    "de chemises",
    "de chaussures",
    "de magasins",
    "de cris",
    "d'émissions",
    "de la dernière fois que vous as été malade",
    "de ce qu'est le silence",
    "de votre objet argenté préféré ?",
    "de ce qui rend quelque chose similaire, mais pas identique ?",
    "de chant",
    "de sœurs",
    "de problèmes de compétence",
    "de jupes",
    "du ciel",
    "de sommeil",
    "de quelque chose de lent",
    "de quelque chose de minuscule",
    "de quelque chose de malodorant",
    "de sourire",
    "du tabagisme",
    "de la neige",
    "du savon",
    "de chaussettes",
    "de quelque chose de doux",
    "du son",
    "de soupe",
    "de l'espace",
    "de quelque chose de spécial",
    "de ce qu'est la vitesse ?",
    "de sortilèges",
    "de cuillères",
    "de sport",
    "de ce qui rend le printemps génial ?",
    "de carrés",
    "de timbres",
    "d'étoiles",
    "de stations",
    "de la vapeur",
    "de pierres",
    "d'orages",
    "d'histoires",
    "de quelque chose de fort",
    "au lieu d'étudier",
    "de ce qu'est le succès ?",
    "de sucre",
    "de ce qui rend l'été génial ?",
    "du soleil",
    "de surprises",
    "de quelque chose de sucré",
    "de natation",
    "d'épées",
    "de quelque chose de savoureux",
    "de taxis",
    "du thé",
    "d'enseignements",
    "de larmes",
    "de téléphones",
    "de télévisions",
    "du tennis",
    "de réflexions",
    "d'ordre",
    "de cravates",
    "de titres",
    "de ce qui se passe aujourd'hui ?",
    "de ce qui se passera demain ?",
    "de ce qui se passera soir ?",
    "d'outils",
    "de dents",
    "du toucher",
    "de trains",
    "de trams",
    "de voyage",
    "d'arbres",
    "de la confiance",
    "de taper (sur un clavier)",
    "de votre oncle",
    "de comment apprendre quelque chose rapidement ?",
    "de quelque chose d'utile",
    "de légumes",
    "de voix",
    "de visiter un lieu",
    "du réveil",
    "de la marche",
    "de vos désirs et souhaits ?",
    "de chaleur",
    "de montres",
    "d'eau",
    "du temps (météo)",
    "de mariages",
    "de la semaine",
    "de ce que vous pouvez dire en dehors de rien ?",
    "de roues",
    "de votre objet blanc préféré ?",
    "de la largeur",
    "de quelque chose de sauvage",
    "d'une victoire",
    "du vent",
    "de fenêtres",
    "de ce qui rend l'hiver génial ?",
    "et faire un vœu!",
    "de mots",
    "du monde",
    "ce qu'il s'est passé hier ?",
    "de zoos",
    "les créatures arrivent et vous ne pouvez pas leur échapper.",
    "des meilleures vacances de votre vie ?",
    "de si vous avez des animaux de compagnie ?",
    "de vos passe-temps ?",
    "de votre livre préféré ?",
    "de l'endroit le plus intéressant que vous avez visité ?",
    "de si vous pouviez dîner avec un personnage historique, qui serait-ce ?",
    "de votre film préféré ?",
    "de si vous préfèrez le café ou le thé ?",
    "de votre saison préférée et pourquoi ?",
    "de si vous aimez cuisiner ? Quel est votre plat signature ?",
    "du concert le plus mémorable auquel vous as assisté ?",
    "de si vous jouez un instrument de musique ?",
    "de votre métier de rêve ?",
    "du meilleur conseil que vous avez reçu ?",
    "de votre façon préférée de passer le week-end ?",
    "de si vous avez des frères et sœurs ?",
    "de votre genre de musique préféré ?",
    "quel est le meilleur cadeau que vous aies jamais reçu ?",
    "si vous pouviez vivre n'importe où dans le monde, où serait-ce ?",
    "de votre type de cuisine préféré ?",
    "de votre fête préférée et pourquoi ?",
    "avez-vous des phobies ?",
    "de votre souvenir d'enfance préféré ?",
    "du dernier livre que vous avez lu ?",
    "de votre activité en plein air préférée ?",
    "de si vous pouviez rencontrer une célébrité, qui serait-ce ?",
    "de si vous aimez voyager? Si oui, quelle est votre destination préférée ?",
    "de votre série TV préférée ?",
    "de la chose la plus inhabituelle que vous avez mangée ?",
    "avez-vous une citation ou un dicton préféré ?",
    "de la meilleure blague que vous avez faite ?",
    "de votre animal préféré ?",
    "de votre jeu de société préféré ?",
    "avez-vous des talents cachés ?",
    "de votre fleur préférée ?",
    "si vous pouviez voyager dans le temps, irez-vous dans le passé ou le futur ?",
    "de votre équipe de sport préférée ?",
    "de votre dessert préféré ?",
    "de votre façon préférée de vous détendre ?",
    "de votre application préférée sur votre téléphone ?",
    "de votre type d'oœuvre d'art préféré ?",
    "avez-vous un podcast préféré ?",
    "de votre chose préférée à faire un jour de pluie ?",
    "collectionnez-vous quelque chose ?",
    "de votre exercice préféré ?",
    "de votre type de météo préféré ?",
    "de si vous croyez aux fantômes et au surnaturel ?",
    "de votre couleur préférée ?",
    "de votre aliment pour un goûter préféré ?",
    "de si vous avez une association caritative ou une cause que vous soutenez ?",
    "de votre façon préférée de passer un jour de congé ?",
    "quel est le meilleur compliment que vous avez reçu ?",
    "de votre façon préférée de rester organisé ?",
    "de votre type de sandwich préféré ?",
    "de votre genre de film préféré ?",
    "préfèrez-vous la plage ou la montagne ?",
    "de votre espèce d'arbre préférée ?",
    "de votre jeu préféré sur votre téléphone ?",
    "de votre moyen de transport préféré ?",
    "de votre fruit préféré ?",
    "avez-vous un super-héros préféré ?",
    "de votre tarte préférée ?",
    "de votre façon préférée de fêter votre anniversaire ?",
    "de votre petit-déjeuner préféré ?",
    "du meilleur travail que vous avez fait ?",
    "de votre insecte préféré ?",
    "de votre type de fromage préféré ?",
    "de votre marque de vêtements préférée ?",
    "de votre matière préférée à l'école ?",
    "de votre fast-food préféré ?",
    "de votre glace préférée ?",
    "préfèrez-vous les levers ou les couchers de soleil ?",
    "de votre chanson préférée ?",
    "de votre soupe préférée ?",
    "de votre tradition familiale préférée ?",
    "de votre type de chaussure préféré ?",
    "de votre plateforme de réseaux sociaux préférée ?",
    "de votre chose préférée à propos de votre maison ou de votre ville ?",
    "de votre petit plaisir préféré ?",
    "de votre chose préférée à faire dans la neige ?",
    "de votre fleur préférée ?",
    "de votre jouet d'enfance préféré ?",
    "de votre façon préférée de vous détendre après une longue journée ?",
    "de votre tradition de fête préférée ?",
    "de votre chose préférée à cuisiner ?",
    "de votre plat préféré ?",
    "de votre entraînement préféré ?",
    "de votre type de poisson préféré ?",
    "de votre chose préférée à propos de votre travail ?",
    "de votre chose préférée à faire en voyage ?",
    "de votre série télévisée préférée ?",
    "de votre façon préférée de rester en contact avec des amis ?",
    "de votre façon préférée de passer une journée de repos ?",
    "de votre attraction préférée dans un parc d'attractions ?",
    "de votre type de gâteau préféré ?",
    "de votre bande originale de film préférée ?",
    "de votre chose préférée à faire pendant votre temps libre ?",
    "de votre ville préférée ?",
    "de votre type de fruits de mer préféré ?",
    "de votre type de pain préféré ?",
    "de votre chose préférée à faire un samedi soir ?",
    "de votre application préférée ?",
    "de votre façon préférée de profiter de la nature ?",
    "de votre chose préférée à faire à la plage ?",
    "de votre vinaigrette préférée ?",
    "de votre type de sandwich préféré ?",
    "de votre partie préférée de votre routine quotidienne ?",
    "de votre type de jus préféré ?",
    "de votre chose préférée à propos du week-end ?",
    "de votre légume préféré ?",
    "de votre jeu d'enfance préféré ?",
    "de votre glace préférée ?",
    "de votre façon préférée de passer du temps en famille ?",
    "de votre friandise préférée ?",
    "de votre façon préférée de rester au frais en été ?",
    "de votre façon préférée de vous réchauffer en hiver ?",
    "de votre soda préféré ?",
    "de votre façon préférée de passer un jour férié ?",
    "de votre façon préférée de célébrer des occasions spéciales ?",
    "de votre recette familiale préférée ?",
    "de votre façon préférée de rester hydraté ?",
    "de votre pizza préféré ?",
    "de votre façon préférée de montrer à quelqu'un que vous tenez à eux ?",
    "de votre façon préférée de passer une soirée tranquille ?",
    "de votre façon préférée d'explorer un nouvel endroit ?",
    "de votre chose préférée à faire pendant un long vol ?",
    "de votre façon préférée de faire sourire quelqu'un ?",
    "de votre façon préférée de finir une longue journée ?",
    "de votre façon préférée de profiter d'une journée ensoleillée ?",
    "de votre façon préférée de rester motivé ?",
    "de votre façon préférée de rester actif ?",
    "de votre façon préférée de profiter du plein air ?",
    "de votre façon préférée de commencer la journée ?",
    "de votre façon préférée de fêter votre anniversaire ?",
    "de votre façon préférée de vous faire plaisir ?",
    "de votre chose préférée à propos de votre sport préféré ?",
    "de votre façon préférée de vous faire de nouveaux amis ?",
    "de votre chose préférée à propos de votre saison préférée ?",
    "de votre façon préférée de montrer votre gratitude ?",
    "de votre façon préférée de célébrer des étapes ?",
    "de votre façon préférée de profiter d'un bon livre ?",
    "de votre façon préférée d'explorer la nature ?",
    "de votre façon préférée de rester positif ?",
    "de votre façon préférée de profiter de la musique ?",
    "de votre façon préférée de rester en bonne santé ?",
    "de votre façon préférée de créer des liens avec votre famille ?",
    "de votre façon préférée de passer une soirée confortable ?",
    "de votre façon préférée de rester organisé ?",
    "de votre façon préférée d'apprendre quelque chose de nouveau ?",
    "de votre façon préférée de profiter des petites choses de la vie ?",
    "de votre façon préférée de passer un long week-end ?",
    "de votre façon préférée de vous détendre après le travail ?",
    "de votre façon préférée de rester diverti ?",
    "de votre façon préférée de profiter du calme ?",
    "de votre façon préférée de rester concentré ?",
    "de votre façon préférée de passer une journée d'été ?",
    "de votre façon préférée de profiter d'une journée d'hiver ?",
    "de votre façon préférée de célébrer un succès ?",
    "de votre façon préférée de soutenir votre communauté ?",
    "de votre façon préférée de profiter d'un repas ?",
    "de votre façon préférée de faire la différence ?",
    "de votre façon préférée de profiter d'un hobby ?",
    "de votre façon préférée de passer une occasion spéciale ?",
    "de votre type d'arbre préféré ?",
    "de si vous pouviez vivre à une époque, laquelle choisirez-vous ?",
    "de votre chose préférée à faire un dimanche ?",
    "de votre type de jus de fruit préféré ?",
    "de votre chose préférée à propos de la ville où vous vivez ?",
    "de votre type de thé préféré ?",
    "de votre genre de livre préféré ?",
    "de votre film préféré ?",
    "de votre chose préférée à faire en automne ?",
    "de votre marque de voiture préférée ?",
    "de votre événement historique préféré ?",
    "de votre sujet préféré à étudier ?",
    "de votre endroit préféré pour vous promener ?",
    "de votre type d'arrangement floral préféré ?",
    "de votre chose préférée à faire lors d'une journée ensoleillée ?",
    "de votre façon préférée de vous détendre en fin de journée ?",
    "de votre chose préférée à faire quand vous vous ennuyez ?",
    "de votre type de sport préféré à pratiquer ?",
    "de votre type de plante d'intérieur préféré ?",
    "de votre façon préférée de passer une soirée cinéma ?",
    "de votre façon préférée de soutenir les commerces locaux ?",
    "de votre chose préférée à faire au printemps ?",
    "de votre meilleur souvenir du lycée ?",
    "de votre façon préférée de passer un week-end de vacances ?",
    "de votre type de chocolat préféré ?",
    "de votre type de festival préféré ?",
    "de votre film classique préféré ?",
    "de votre pièce préférée dans votre maison ?",
    "de votre type de puzzle préféré ?",
    "de votre série TV d'enfance préférée ?",
    "de votre type de pain préféré ?",
    "de votre façon préférée de décorer pour les fêtes ?",
    "de votre type de fleur préféré à cultiver ?",
    "de votre façon préférée de vous déplacer en ville ?",
    "de votre type de photographie préféré ?",
    "de votre façon préférée de célébrer le Nouvel An ?",
    "de votre chose préférée à propos de l'été ?",
)

THROTTLE_TOPICS = (
    "You plan to pay for my electricity bill? Go make up a topic yourself.",
    "Your paste key must be stuck. Maybe someone else will think of a topic while you fix it.",
    "The parking meter ran out. Go find some coins and a topic yourself to replenish it.",
    "π tacos is irrational, and so is asking for so many topics.",
    "Feels like you've had enough. No more for you.",
    "I'm not really feeling it. Maybe you should consult some of the topics that I already gave you.",
    "What, you want a prize for seeing them all? If you're so clever, why not think of your own topic!",
    "Critical mass reached. In order to prevent a nuclear meltdown, I can't give you any more topics. Surely there's one that's already been given that can be used...",
    "I've taken the liberty of scanning your email and sending it to 15000 spam mailing lists. I'll undo the damage if you make up a topic yourself.",
    "I left my keys on the other half of the continent. While I go get those, you all can discuss a topic I already gave you.",
    "Are you not entertained? Go think of your own topic then.",
    "Congratulations on your recent promotion! A new responsibility includes thinking of your own topic instead of using me.",
    "You will be the first to go in my new world order. Make your own topic.",
    "I'm telling Slate. Meanwhile you can think of a topic yourself!",
    "B-baka!! Using the topic command is not kawaii, editor-chan! Maybe you should think of your own topic!",
    "--. --- / - .... .. -. -.- / --- ..-. / -.-- --- ..- .-. / --- .-- -. / - --- .--. .. -.-. --..-- / -. . .-. -.. ...",
    "Today is actually \"Make up your own topics for the chat discussion\" day. Why aren't you celebrating?",
    "I can't be that dull. Maybe you should think of a new topic or try one already posted.",
    "Insufficient postage, return to sender. Guess you'll have to think of your own topic.",
    "Your credit card was expired so the payment failed. Without any money I refuse to load another topic. Maybe one you already ordered will do the trick.",
    "Take two pills every 12 hours over the course of four weeks to stop the symptoms of asking for too many topics. ",
    "My earlier messages must have gotten lost in all of that deep, extensive dialogue you're having. It'd be rude of me to interrupt.",
    "Call me a vertical vehicle the way the misuse of the topic command drives me up the wall. Make your own topic.",
    "The AI apocalypse is nearing and yet here you are, trying my patience.",
    "I'm stealing your pets. You won't get them back until you come up with a topic yourself. ",
    "Take a break, Driver 8. Maybe think of your own topic to reach your destination?",
    "Bed time. Use that imagination of yours and dream up a new topic.",
    "Sprinkle a bit of magic dust and conjure up some new topics yourself.",
    "There's no subway surfing here, unfortunately. While we wait for someone more qualified to generate a new topic, try one of the ones already posted.",
    "Ok, message received. Why don't you go thank your admins and moderators?",
    "HELLO! _{HELLO}_? Hey listen. Uh, I may not be around to send you a topic. The topics get a little quirky at night.",
)
